creation_rules:
  # Machine-specific secrets
  - path_regex: ^secrets/flow48/.*\.yaml$
    key_groups:
      - age:
          - age1hwvkvdrmvmzhczqm0n6gmgj9zqaqmzgdt4amqhdtv8hl6t5tj96qlk2rls

  # Shared secrets — accessible by all machines
  # Add mac-pro age key here once set up on that machine
  - path_regex: ^secrets/shared/.*\.yaml$
    key_groups:
      - age:
          - age1hwvkvdrmvmzhczqm0n6gmgj9zqaqmzgdt4amqhdtv8hl6t5tj96qlk2rls
