name: check

on:
  push:
    branches: [main]
  pull_request:

jobs:
  flake-check:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v5
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix flake check --no-build

  build:
    runs-on: macos-14
    strategy:
      matrix:
        host: [mac-pro, flow48]
    steps:
      - uses: actions/checkout@v5
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix build ".#darwinConfigurations.${{ matrix.host }}.system" --no-link
